version: 1.0
learning:
  rate: 0.1
  memory_size: 1000
  update_interval_seconds: 60
networking:
  sniffer_database: "packets.db"
  translator_url: "http://localhost:8888"
  max_packet_queue: 1000
decision_making:
  confidence_threshold: 0.6
  max_latency_ms: 50
  max_throughput: 20
  fallback_protocol: "HTTP"
security:
  anomaly_detection: true
  rate_limiting: true
  max_connections_per_second: 100
logging:
  level: "INFO"
  file: "upt_agent.log"
  max_size_mb: 10
  multicast:
  group: "239.255.0.1"
  port: 5000
  ttl: 2
  secret_key: "upt_secure_2025"